### ISSUE TITLE
Async Connection implementation

### ISSUE THREAD

**Issue by dilipvamsi** [ArangoDB-Community/pyArango#136]
Hi @tariqdaouda @dothebart 
Currently connection is implemented doesn't support async calls to fetch the data. 
Are there any plans for implementing this.
If not lets plan and design a version.
So, I can start working on it. 

Regards, 
Dilip Vamsi.

**Comment by dothebart** [comment]
Do you mean implementing 
https://docs.arangodb.com/3.4/HTTP/AsyncResultsManagement/  ? 
Probably having a closer look at the java driver could be a good idea then.

**Comment by dilipvamsi** [comment]
No, 
I was talking about the async connection (connecting using async calls) to arangodb which can be used in tornado or asyncio.
So, the io waiting will not be a busy waiting.

**Comment by dothebart** [comment]
ah, did you see our work with greenlets? will that be similar - aka a third way to switch the aikido session, and done?

**Comment by dilipvamsi** [comment]
The connection which does the rest calls cannot be called as it is going to be async.
So, all the functions have to be changed to async. (essentially most of the code has be changed to incorporate this functionality). 
May be a completely different repo all together

**Comment by dothebart** [comment]
hm, for the ease of the implementation, greenlets don't work for you? since they solve all this async sh* in a pretty readable manner - even better than futures etc.

**Comment by tariqdaouda** [comment]
pyArango should either with requests (sync) or with greenlets (sync/async). Arango is usually fast enough that async requests are not worth the additional hassle (syncing data, cursors dying on you etc..).

**Comment by dilipvamsi** [comment]
okay, lets close this for now.

**Comment by bgmnbear** [comment]
Hi.

I met the same question on my tornado project, I don't know what method you use to fetch data from ArangoDB by pyArango. Anyway, I use **Celery** Task to fetch data, maybe doesn't async call either, and I found that pyArango connection will be warning on Celery when I async call concurrently. Here is the warning: 

> Unable to establish connection, perhaps arango is not running.

So that the error occurs on pyArango/connection.py, 45 line, and the Celery will raise error and doesn't work.

Finally, I use **python-arango** to solve the problem. May this review help you.

Best,
Whister.
